version: "3"
services:
  elasticsearch:
    init: true
    container_name: elasticsearch
    expose:
      - "9200"
    build:
      context: elasticsearch/
      args:
        ELK_VERSION: ${ELK_VERSION}

    ports:
      - "9200:9200"
      - "9300:9300"

    environment:
      ES_JAVA_OPTS: -Xms256m -Xmx256m
      discovery.type: single-node
